version: "3.4"

services:
  statping:
    image: statping/statping:latest
    environment:
      - "DB_CONN=postgres"
      - "DB_HOST=db"
      - "DB_USER=<dbusername>"
      - "DB_PASS=<dbpassword>"
      - "DB_DATABASE=statpingdb"
      - "NAME=Uptime Monitor"
      - "DESCRIPTION=Statping Uptime Monitor"
    volumes:
      - /share/appdata/statping:/app
    networks:
      - traefik_public
      - internal
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.statping.rule=Host(`statping.gkoerk.com`)"
        - "traefik.http.routers.statping.middlewares=forward-auth@file"
        - "traefik.http.services.statping.loadbalancer.server.port=8080"

  db:
    image: postgres:10
    networks:
      - internal
    volumes:
      - /share/runtime/statping:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=<dbpassword>"
      - "POSTGRES_USER=<dbusername>"
      - "POSTGRES_DB=statpingdb"

  db-backup:
    image: postgres:10
    environment:
      - PGUSER=<dbusername>
      - PGPASSWORD=<dbpassword>
      - PGHOST=db
      - BACKUP_NUM_KEEP=7
      - BACKUP_FREQUENCY=1d
    volumes:
      - /share/appdata/statping/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        pg_dump -Fc > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.psql
        (ls -t /dump/dump*.psql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.psql)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    networks:
      - internal

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.75.0/24
