# Traefik 2.0 Recipe
# /share/appdata/config/traefik/traefik.yml
version: "3.4"

secrets:
  namecheap_api_key:
    file: "/share/appdata/config/secrets/namecheap_api_key.secret"

services:
  app:
    image: traefik:latest
    secrets:
      - namecheap_api_key
    environment:
      - NAMECHEAP_API_USER=gkoerk
      - NAMECHEAP_API_KEY_FILE=/run/secrets/namecheap_api_key
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8090
        protocol: tcp
        mode: host
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - /share/appdata/config/traefik:/etc/traefik
       - /share/appdata/config/certs:/etc/traefik/certs:rw
    networks:
      - traefik_public
    command: --configFile=/etc/traefik/traefik-static.yaml
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.gkoerk.com`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.middlewares=forward-auth@file"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  auth:
    image: dniel/forwardauth:2.0-rc1
    networks:
      - traefik_public
    ports:
      - 8080:8080
    volumes:
      - /share/appdata/config/traefik/application.yaml:/config/application.yaml
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.auth.rule=Host(`auth.gkoerk.com`)"
        - "traefik.http.routers.whoami.middlewares=forward-auth@file"
        - "traefik.http.services.auth.loadbalancer.server.port=8080"

  whoami:
    image: containous/whoami:latest
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.gkoerk.com`)"
        - "traefik.http.routers.whoami.middlewares=forward-auth@file"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"

  httpbin:
    image: kennethreitz/httpbin:latest
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.httpbin.rule=Host(`httpbin.gkoerk.com`)"
        - "traefik.http.services.httpbin.loadbalancer.server.port=80"

  www:
    image: dniel/blogr-www
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.www.rule=Host(`www.gkoerk.com`)"
        - "traefik.http.routers.www.middlewares=forward-auth@file"
        - "traefik.http.services.www.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
