# Traefik Static Configuration
# Host Path: /share/appdata/config/traefik/traefik-static.yaml
# Internal Path: /etc/traefik/dynamic/traefik-static.yaml

global:
  checkNewVersion: true

entryPoints:

  http:
    address: ":80"
    # Trust IPv4 Private Address Space
    forwardedHeaders:
      trustedIPs:
      - "172.16.0.0/12"
      - "10.0.0.0/8"
      - "192.168.0.0/16"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
          priority: 300

  https:
    address: ":443"
    # Trust IPv4 Private Address Space
    forwardedHeaders:
      trustedIPs:
      - "172.16.0.0/12"
      - "10.0.0.0/8"
      - "192.168.0.0/16"
    http:
      # middlewares:
      #  - forward-auth@file
      tls:
        options: default
        certResolver: namecheap
        domains:
          - main: gkoerk.com
            sans:
            - "*.gkoerk.com"
          - main: qnapunofficial.com
            sans:
            - "*.qnapunofficial.com"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock" 
    # Alternative endpoint:
    # endpoint: "tcp://127.0.0.1:2375"
    watch: true
    swarmMode: true
    network: traefik_public
    useBindPortIP: false
    exposedByDefault: false

  file:
    filename: /etc/traefik/traefik-dynamic.yaml
    # Optional instead of filename:
    # directory: /etc/traefik/dynamic
    watch: true
    debugLogGeneratedTemplate: false

  rest:
    insecure: true

api:
  dashboard: true
# Enable insecure: true for testing/development mode only.
  # insecure: true
  # debug: true

log:
  # DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  level: ERROR
  filePath: "/etc/traefik/traefik.log"

# accessLog:
#   filePath: "/etc/traefik/access.log"

certificatesResolvers:
  namecheap:
    acme:
      email: "gkoerk@gmail.com"
      storage: "/etc/traefik/acme.json"
      # Alternative ACME Staging CA Server (not ratelimited like prod):
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      # Prod ACME Staging CA Server (ratelimited):
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: namecheap
        delayBeforeCheck: 30
        resolvers:
        - "1.1.1.1:53"
        - "8.8.8.8:53"
