version: "3.4"

services:
  nextcloud:
    image: nextcloud:latest
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=<adminpass>
      - "NEXTCLOUD_TRUSTED_DOMAINS=192.168.1.100 10.*.*.* 172.16.*.* 192.168.*.* *.gkoerk.com *.nextcloud.com"
      - NEXTCLOUD_DATA_DIR=/datadir
      - MYSQL_HOST=db
      - MYSQL_DATABASE=<dbname>
      - MYSQL_USER=<dbuser>
      - MYSQL_PASSWORD=<dbpass>
      - REDIS_HOST=redis
      - REDIS_HOST_PORT:6379
      - APACHE_DISABLE_REWRITE_IP=1
      - "TRUSTED_PROXIES=192.168.1.100 10.*.*.* 172.16.*.* 192.168.*.* traefik.gkoerk.com traefik"
    # Enable the following for http://server_ip:11245
    # ports:
    #   - 11245:80
    volumes:
      - /share/appdata/nextcloud:/var/www/html
      - /share/nextcloud:/datadir
      - /dev/urandom:/dev/urandom:ro
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.gkoerk.com`)"
        - "traefik.http.routers.nextcloud.middlewares=nextcloud-chain@file"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

  # adminer:
  #   image: adminer:latest
  #   networks:
  #     - internal
  #     - traefik_public
  #   deploy:
  #     labels:
  #       - "traefik.enable=true"
  #       - "traefik.http.routers.nextadmin.rule=Host(`nextadmin.gkoerk.com`)"
  #       - "traefik.http.routers.nextadmin.middlewares=basic-user@file"
  #       - "traefik.http.services.nextadmin.loadbalancer.server.port=8080"

  db:
    image: mariadb:10
    environment:
      # For database backup (keep 7 days daily backups)
      - MYSQL_ROOT_PASSWORD=<dbrootpass>
      - MYSQL_DATABASE=<dbname>
      - MYSQL_USER=<dbuser>
      - MYSQL_PASSWORD=<dbpass>
    volumes:
      - /share/runtime/nextcloud/db:/var/lib/mysql
    networks:
      - internal

  db-backup:
    image: mariadb:10
    environment:
      # For database backup (keep 7 days daily backups)
      - MYSQL_PWD=<dbrootpass>
      - MYSQL_USER=root
      - BACKUP_NUM_KEEP=7
      - BACKUP_FREQUENCY=1d
    volumes:
      - /share/appdata/nextcloud-backup/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        mysqldump -h db --all-databases | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        (ls -t /dump/dump*.sql.gz|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql.gz)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    networks:
      - internal

  # db-restore:
  #   image: mariadb:10
  #   volumes:
  #     - /share/appdata/nextcloud-backup/database-dump:/dump
  #     - /etc/localtime:/etc/localtime:ro
  #   networks:
  #     - internal

  redis:
    image: redis:alpine
    volumes:
      - /share/runtime/nextcloud/redis:/data
    networks:
      - internal

  # elasticsearch:
  #   image: elasticsearch:5.6-alpine
  #   volumes:
  #     - /share/runtime/nextcloud/elasticsearch:/usr/share/elasticsearch/data
  #   environment:
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
  #   networks:
  #     - internal
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 2048M
  #       reservations:
  #         memory: 2048M
  #
  # solr:
  #   image: solr:6-alpine
  #   volumes:
  #     - /share/runtime/nextcloud/solr:/opt/solr/server/solr/mycores
  #   entrypoint:
  #     - docker-entrypoint.sh
  #     - solr-precreate
  #     - nextant
  #   networks:
  #     - internal

  cron:
    image: nextcloud:latest
    environment:
      - NEXTCLOUD_DATA_DIR=/datadir
    volumes:
      - /share/appdata/nextcloud:/var/www/html
      - /share/nextcloud:/datadir
    user: www-data
    entrypoint: |
      bash -c 'bash -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM
        while [ ! -f /var/www/html/config/config.php ]; do
          sleep 1
        done
        while true; do
          php -f /var/www/html/cron.php
          sleep 15m
        done
      EOF'
    networks:
      - internal

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.12.0/24
