version: "3.4"

services:
  teedy:
    image: sismics/docs:latest
    environment:
      - DOCS_BASE_URL=https://teedy.gkoerk.com
    volumes:
      - /share/appdata/teedy:/data
    networks:
      - traefik_public
      - internal
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.teedy.rule=Host(`teedy.gkoerk.com`)"
        - "traefik.http.routers.teedy.middlewares=forward-auth@file"
        - "traefik.http.services.teedy.loadbalancer.server.port=8080"

  importer:
    image: cornelicorn/teedy-importer:latest
    environment:
      - TEEDY_ADDTAGS=false
      - TEEDY_LANG=eng
      - 'TEEDY_URL=https://teedy.gkoerk.com'
      - TEEDY_USERNAME=<username>
      - TEEDY_PASSWORD=<password>
    volumes:
      - /share/downloads/scanned_files:/import
    networks:
      - internal

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.66.0/24
