version: "3.4"
services:

  wikijs:
    image: linuxserver/wikijs:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /share/appdata/wikijs/config:/config
      - /share/appdata/wikijs/data:/data
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wikijs.rule=Host(`wiki.gkoerk.com`)"
        - "traefik.http.services.wikijs.loadbalancer.server.port=3000"

networks:
  traefik_public:
    external: true
